name: Quick Check

on:
  push:
  pull_request:

jobs:
  quick-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5

    - name: Install uv
      uses: astral-sh/setup-uv@v6
      with:
        version: "latest"

    - name: Set up Python
      run: uv python install 3.12

    - name: Install dependencies
      run: uv sync --dev

    - name: Check code formatting
      run: uv run ruff format --check .

    - name: Lint code
      run: uv run ruff check .

    - name: Run tests
      run: uv run pytest --tb=short